# Generated by Django 2.2 on 2020-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataabase',
            name='session_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
